import { ANATOMY } from './data/anatomy.js';
import { EVENTS } from './data/events.js';
import { SEQUENCE } from './data/sequence.js';

const title=document.getElementById('regionTitle'),desc=document.getElementById('description'),eyebrow=document.getElementById('eyebrow'),facts=document.getElementById('facts'),context=document.getElementById('contextBanner');
let selectedRegion=null,selectedEvent=null,currentMode='anatomy',sequenceIndex=0;
function renderFacts(items){facts.innerHTML=items.map(f=>`<div class="fact"><b>${f[0]}</b><span>${f[1]}</span></div>`).join('');}
function setTab(mode){currentMode=mode;const anatomy=document.getElementById('anatomyTab'),event=document.getElementById('eventTab');anatomy.classList.toggle('active',mode==='anatomy');event.classList.toggle('active',mode==='event');anatomy.setAttribute('aria-selected',mode==='anatomy');event.setAttribute('aria-selected',mode==='event');}
function highlightRegion(id){document.querySelectorAll('.region').forEach(x=>x.classList.toggle('active',x.dataset.region===id));selectedRegion=id;}
function showAnatomy(id){const d=ANATOMY[id];if(!d)return;setTab('anatomy');highlightRegion(id);title.textContent=d.title;desc.textContent=d.desc;eyebrow.textContent=d.eye;renderFacts(d.facts);context.innerHTML='<strong>Anatomy mode:</strong> You selected '+d.title+'. Click another region to compare its normal role and seizure-related factors.';}
function showEvent(ev,el){selectedEvent=ev;setTab('event');highlightRegion(ev.region);document.querySelectorAll('.event').forEach(x=>x.classList.toggle('active',x===el));title.textContent=ev.name;eyebrow.textContent='Observed event interpretation';desc.textContent=ev.summary;renderFacts([['Why it may raise seizure concern',ev.factors],['Important mimics',ev.mimics],['What to document',ev.document],['Clinical boundary','This pattern is not diagnostic. Evaluation depends on history, examination, medication and metabolic review, and testing when clinically indicated.']]);context.innerHTML='<strong>Observed-event mode:</strong> The highlighted anatomy is one plausible network association, not proof of seizure onset.';}
document.querySelectorAll('.region').forEach(x=>{x.setAttribute('tabindex','0');x.setAttribute('role','button');x.setAttribute('aria-label',`Show ${ANATOMY[x.dataset.region]?.title || x.dataset.region} details`);x.addEventListener('click',()=>showAnatomy(x.dataset.region));x.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showAnatomy(x.dataset.region);}});});
const eventBox=document.getElementById('events');function renderEvents(q=''){const matches=EVENTS.filter(e=>(e.name+' '+e.summary+' '+e.mimics).toLowerCase().includes(q.toLowerCase()));eventBox.innerHTML=matches.length?matches.map(e=>`<button class="event" data-i="${EVENTS.indexOf(e)}">${e.name}<small>${e.summary}</small></button>`).join(''):'<p class="empty-state">No matching observed events.</p>';eventBox.querySelectorAll('.event').forEach(el=>el.onclick=()=>showEvent(EVENTS[+el.dataset.i],el));}renderEvents();document.getElementById('search').oninput=e=>renderEvents(e.target.value);
document.getElementById('anatomyTab').onclick=()=>{if(selectedRegion)showAnatomy(selectedRegion);else resetInfo();};
document.getElementById('eventTab').onclick=()=>{if(selectedEvent){const el=[...document.querySelectorAll('.event')].find(x=>+x.dataset.i===EVENTS.indexOf(selectedEvent));showEvent(selectedEvent,el);}else{setTab('event');title.textContent='Choose an observed event';eyebrow.textContent='Observed event interpretation';desc.textContent='Select an event from the list to see a possible network association, seizure-related features, mimics, and documentation priorities.';renderFacts([['Important','No observed behavior by itself confirms a seizure. Pattern, timing, recurrence, recovery, and competing explanations matter.']]);context.innerHTML='<strong>Observed-event mode:</strong> Choose an event from the list.';}};
function setView(v){document.querySelectorAll('[data-view]').forEach(x=>{const active=x.dataset.view===v;x.classList.toggle('active',active);x.setAttribute('aria-pressed',active);});const internal=v==='internal';document.getElementById('internal').style.opacity=internal?1:0;document.getElementById('internal').style.pointerEvents=internal?'auto':'none';document.getElementById('internalLabels').classList.toggle('visible',internal);document.getElementById('internalKey').classList.toggle('visible',internal);document.getElementById('labels').style.opacity=internal?'.25':'1';document.getElementById('sequencePanel').classList.toggle('visible',v==='sequence');setNetworkVisible(v==='sequence');if(internal){showAnatomy('hippocampus');}else if(v==='sequence'){sequenceIndex=0;renderSequence();}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function setNetworkVisible(show){for(let i=1;i<=3;i++)document.getElementById('path'+i).classList.toggle('visible',show);for(let i=1;i<=4;i++)document.getElementById('node'+i).classList.toggle('visible',show);}
function renderSequence(){const s=SEQUENCE[sequenceIndex];document.getElementById('sequenceStep').textContent=`Step ${sequenceIndex+1} of ${SEQUENCE.length}`;document.getElementById('sequenceTitle').textContent=s.title;document.getElementById('sequenceCopy').textContent=s.copy;for(let i=1;i<=3;i++)document.getElementById('path'+i).classList.toggle('active',i<=s.paths);for(let i=1;i<=4;i++)document.getElementById('node'+i).classList.toggle('active',i<=s.nodes);highlightRegion(s.region);setTab('anatomy');eyebrow.textContent='Example network sequence';title.textContent=s.title;desc.textContent=s.copy;renderFacts([['What the diagram means','Numbered points show a staged educational example of network recruitment. The lines do not represent a fixed pathway that every seizure follows.'],['Observable consequences','Manifestations depend on the networks involved and may include memory interruption, behavioral arrest, speech disturbance, automatisms, motor signs, or reduced responsiveness.'],['Clinical limitation','This sequence illustrates pathophysiologic concepts and cannot determine whether an observed event was a seizure.']]);context.innerHTML='<strong>Network-sequence mode:</strong> Use Previous and Next. The pathway is static and staged so each step has an explanation.';}
document.getElementById('prevStep').onclick=()=>{sequenceIndex=Math.max(0,sequenceIndex-1);renderSequence();};document.getElementById('nextStep').onclick=()=>{sequenceIndex=Math.min(SEQUENCE.length-1,sequenceIndex+1);renderSequence();};document.getElementById('exitSequence').onclick=()=>setView('lobes');
function resetInfo(){setTab('anatomy');selectedRegion=null;title.textContent='Human Brain, Lateral View';eyebrow.textContent='Orientation';desc.textContent='Select a colored brain region or choose an observed event. The brain highlight and explanation update together while remaining on screen.';renderFacts([['How to use','Tap a lobe to review anatomy, choose an observed event, or open the staged network sequence.'],['Clinical boundary','This tool supports observation and education. It does not diagnose seizures or epilepsy.']]);context.innerHTML='<strong>Anatomy mode:</strong> Click any colored brain region. The description and seizure-related factors appear here.';}
document.getElementById('reset').onclick=()=>{document.querySelectorAll('.event').forEach(x=>x.classList.remove('active'));selectedEvent=null;document.getElementById('search').value='';renderEvents();document.getElementById('internal').style.opacity=0;document.getElementById('internal').style.pointerEvents='none';document.getElementById('internalLabels').classList.remove('visible');document.getElementById('internalKey').classList.remove('visible');document.getElementById('labels').style.opacity=1;document.getElementById('sequencePanel').classList.remove('visible');setNetworkVisible(false);for(let i=1;i<=3;i++)document.getElementById('path'+i).classList.remove('active');document.querySelectorAll('[data-view]').forEach(x=>{const active=x.dataset.view==='lobes';x.classList.toggle('active',active);x.setAttribute('aria-pressed',active);});document.querySelectorAll('.region').forEach(x=>x.classList.remove('active'));resetInfo();};
